-- MySQL Script generated by MySQL Workbench
-- Mon 20 Dec 2021 11:42:43 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mapjournalDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mapjournalDB` ;

-- -----------------------------------------------------
-- Schema mapjournalDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mapjournalDB` ;
USE `mapjournalDB` ;

-- -----------------------------------------------------
-- Table `mapjournalDB`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`location` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(90) NULL,
  `latitude` DECIMAL(9,7) NOT NULL,
  `longitude` DECIMAL(10,7) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapjournalDB`.`pin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`pin` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`pin` (
  `pin_id` INT NOT NULL AUTO_INCREMENT,
  `pin_location` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `moment` VARCHAR(10) NOT NULL,
  `description` VARCHAR(90) NULL,
  `comments` MEDIUMTEXT NULL,
  PRIMARY KEY (`pin_id`),
  INDEX `fk_pin_location_idx` (`pin_location` ASC) VISIBLE,
  CONSTRAINT `fk_pin_location`
    FOREIGN KEY (`pin_location`)
    REFERENCES `mapjournalDB`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapjournalDB`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`tag` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapjournalDB`.`pin_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`pin_tag` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`pin_tag` (
  `pt_pin_id` INT NOT NULL,
  `pt_tag_id` INT NOT NULL,
  PRIMARY KEY (`pt_pin_id`, `pt_tag_id`),
  INDEX `fk_tag_id_idx` (`pt_tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_pt_pin_id`
    FOREIGN KEY (`pt_pin_id`)
    REFERENCES `mapjournalDB`.`pin` (`pin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pt_tag_id`
    FOREIGN KEY (`pt_tag_id`)
    REFERENCES `mapjournalDB`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapjournalDB`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`trip` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`trip` (
  `trip_id` INT NOT NULL AUTO_INCREMENT,
  `trip_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`trip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapjournalDB`.`pin_trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapjournalDB`.`pin_trip` ;

CREATE TABLE IF NOT EXISTS `mapjournalDB`.`pin_trip` (
  `ptr_pin_id` INT NOT NULL,
  `ptr_trip_id` INT NOT NULL,
  PRIMARY KEY (`ptr_pin_id`, `ptr_trip_id`),
  INDEX `fk_ptr_trip_id_idx` (`ptr_trip_id` ASC) VISIBLE,
  CONSTRAINT `fk_ptr_pin_id`
    FOREIGN KEY (`ptr_pin_id`)
    REFERENCES `mapjournalDB`.`pin` (`pin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ptr_trip_id`
    FOREIGN KEY (`ptr_trip_id`)
    REFERENCES `mapjournalDB`.`trip` (`trip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
